# Generated by Django 4.2.10 on 2024-07-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceRequest',
        ),
    ]
