# Generated by Django 4.2.10 on 2024-07-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerequest',
            name='project',
        ),
    ]
