# Generated by Django 4.2.10 on 2024-07-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectupdate_projectassignment'),
        ('finance', '0004_remove_financerequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
