# Generated by Django 4.2.10 on 2024-06-21 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('man_days', models.FloatField(blank=True, null=True)),
                ('total_achievement', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('remaining_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('remaining_time_days', models.CharField(blank=True, max_length=100, null=True)),
                ('remaining_interview', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('reason_for_adjustment', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, choices=[('', '---SELECT---'), ('setup', 'SETUP'), ('onhold', 'ONHOLD'), ('inprogress', 'INPROGRESS'), ('completed', 'COMPLETED')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
