# Generated by Django 4.2.10 on 2024-07-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_projectupdate_delete_operationteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='status',
            field=models.CharField(choices=[('Project Initiated', 'Project Initiated'), ('To Be Started', 'To Be Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='To Be Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='total_achievement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
