# Generated by Django 4.2.10 on 2024-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_rename_project_projectupdate_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='initial_man_days_filled',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
