# Generated by Django 4.2.10 on 2024-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_alter_projectupdate_initial_man_days_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='status',
            field=models.CharField(choices=[('Project_Initiated', 'Project Initiated'), ('To_Be_Started', 'To Be Started'), ('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('On_Hold', 'On Hold')], default='In_Progress', max_length=20),
        ),
    ]
