# Generated by Django 4.2.10 on 2024-08-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_projectupdate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='status',
            field=models.CharField(choices=[('Project Initiated', 'Project Initiated'), ('To Be Started', 'To Be Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='In Progress', max_length=20),
        ),
    ]
