# Generated by Django 4.2.10 on 2024-07-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_sales_owner_remove_project_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finance',
        ),
        migrations.DeleteModel(
            name='ProjectTracking',
        ),
    ]
