# Generated by Django 4.2.10 on 2024-07-12 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_company'),
        ('project', '0003_delete_finance_delete_projecttracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('man_days_filled', models.FloatField()),
                ('total_man_days', models.FloatField()),
                ('remaining_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_achievement', models.CharField(blank=True, default='INPROGRESS', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='project.project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects_by', to='user.userrole')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects_to', to='user.userrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
