# Generated by Django 4.2.10 on 2024-07-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectupdate_projectassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectManager',
        ),
        migrations.DeleteModel(
            name='SalesOwner',
        ),
    ]
