# Generated by Django 4.2.10 on 2024-07-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectupdate_remaining_interview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCode',
        ),
    ]
