# Generated by Django 4.2.10 on 2024-07-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUpdate',
        ),
    ]
