# Generated by Django 4.2.10 on 2024-07-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectassignment',
            old_name='project',
            new_name='project_id',
        ),
    ]
