# Generated by Django 4.2.10 on 2024-08-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdateddata',
            name='project_code',
        ),
        migrations.AddField(
            model_name='projectupdateddata',
            name='project_id',
            field=models.IntegerField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
