# Generated by Django 4.2.10 on 2024-08-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_projectupdateddata_project_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
